SET REFERENTIAL_INTEGRITY = FALSE;

TRUNCATE TABLE diary;
TRUNCATE TABLE diary_content;
TRUNCATE TABLE member;
TRUNCATE TABLE refresh_token;
TRUNCATE TABLE notification;
TRUNCATE TABLE `group`;

SET REFERENTIAL_INTEGRITY = TRUE;